<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- NuGet Package Metadata -->
        <PackageId>EntityFrameworkCore.InterfaceSets</PackageId>
        <Version>1.0.1</Version>
        <Authors>SamuelRe</Authors>
        <Description>A library for Entity Framework Core that enables querying entities through shared interfaces, allowing you to work with entities from different class hierarchies that implement a common interface.</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/SamuelReithmeir/EntityFrameworkCore.InterfaceSets</PackageProjectUrl>
        <RepositoryUrl>https://github.com/SamuelReithmeir/EntityFrameworkCore.InterfaceSets</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>EntityFrameworkCore;efcore;interface;query;linq</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes>Performance improvements and fix for interfaces on basetypes not in the model</PackageReleaseNotes>

        <!-- Generate XML documentation -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.23" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configuration\" />
    </ItemGroup>

</Project>
